version: '3.6'

volumes:
  postgres_data:

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev.backend
    command: bash -c "yarn install && yarn start:dev"
    depends_on:
      - postgres
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 5000:5000

  postgres:
    image: postgres:11.6-alpine
    environment:
      POSTGRES_DB: trello
      POSTGRES_USER: trello
      POSTGRES_PASSWORD: trello
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 6432:5432
