version: '3.6'

volumes:
  postgres_data:

services:
  postgres:
    image: postgres:11.6-alpine
    environment:
      POSTGRES_DB: trello
      POSTGRES_USER: trello
      POSTGRES_PASSWORD: trello
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 6432:5432
